server:
  port: 8081
spring:
  datasource:
#    username: postgres
    #    password: 11111111
    #    url: jdbc:postgresql://localhost:5432/expense_management
    username: mmtxkkre
    password: 0uCdcveeXmzwNiex4d78VuYFqR9tXSwK
    url: jdbc:postgresql://tiny.db.elephantsql.com/mmtxkkre
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  messages:
    basename: i18n/messages
  web:
    locale: vi
    locale-resolver: fixed

viet:
  app:
    jwtExpirationMs: 6000000
    jwtRefreshExpirationMs: 86400000
    jwtSecret: helohehehihi
    cloud_name: drul2rlhe
    api_key: 624968573896295
    api_secret: wJchJWfJ8iUNXsYVoM__61YaTzI

email:
  fromEmail: bookingcare666@gmail.com
  password: bmoqhrufffwexozg



