server:
  port: 8081
spring:
  datasource:
    password: 11111111
    url: jdbc:postgresql://localhost:5432/expense_management
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  messages:
    basename: i18n/messages
  web:
    locale: vi
    locale-resolver: fixed

viet:
  app:
    jwtExpirationMs: 600000
    jwtRefreshExpirationMs: 86400000
    jwtSecret: helohehehihi

email:
  fromEmail: bookingcare666@gmail.com
  password: bmoqhrufffwexozg



